#define SENSOR_TOUCH_FRONT_IN IN_1
#define LIGHT_SENSOR_IN IN_2
#define SENSOR_TOUCH_BACK_IN IN_3
#define ULTRASONIC_IN IN_4

#define SENSOR_LIGHT_EDGE SENSOR_2

#define MOTOR_RIGHT_OUT OUT_A
#define MOTOR_LEFT_OUT OUT_B

#define ENGINE_POWER 50

